Add header paths for system libraries as SYSTEM
This ensures correct include ordering and hides warnings coming
from unrelated code. Specifically, it fixes build on FreeBSD,
which otherwise fails due to to problem in lcms code:

    In file included from .../stratagus-3.3.1/src/action/action_defend.cpp:45:
    In file included from .../stratagus/work/stratagus-3.3.1/src/include/ui.h:56:
    In file included from .../stratagus-3.3.1/src/include/viewport.h:34:
    In file included from .../stratagus-3.3.1/src/include/fow.h:39:
    In file included from .../stratagus-3.3.1/src/include/video.h:228:
    In file included from /usr/local/include/libmng.h:385:
    In file included from /usr/local/include/libmng_types.h:181:
    /usr/local/include/lcms.h:1238:29: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
    typedef int (* _cmsSAMPLER)(register WORD In[],
                                ^~~~~~~~~